apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: clinicalnote
    version: v1
  name: clinicalnote
  namespace: dhcims-msapoc-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clinicalnote
  template:
    metadata:
      labels:
        app: clinicalnote
        version: v1
    spec:
      containers:
      - name: clinicalnote
        env:
        - name: TZ
          value: Asia/Shanghai
        - name: ORACLE_USER
          valueFrom:
            secretKeyRef:
              name: clinicalnote-oracle
              key: user
        - name: ORACLE_PWD
          valueFrom:
            secretKeyRef:
              name: clinicalnote-oracle
              key: pwd
        image: <image-name>
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 600m
            memory: 1536Mi
          requests:
            cpu: 200m
            memory: 512Mi
        volumeMounts:
        - mountPath: /opt/webserver/lib/application.properties
          name: application-config
          subPath: application.properties
        - mountPath: /opt/webserver/lib/logback.xml
          name: logs-config
          subPath: logback.xml
      volumes:
      - configMap:
          items:
          - key: application.properties
            path: application.properties
          name: clinicalnote-config
        name: application-config
      - configMap:
          items:
          - key: logback.xml
            path: logback.xml
          name: clinicalnote-logs
        name: logs-config